# Project information
site_name: DemocracySim
site_description: Welcome to the documentation of the DemocracySim project and its accompanying master thesis.
site_url: https://jurikane.github.io/DemocracySim/
site_author: Paul Kühnel

# Repository
repo_url: https://github.com/jurikane/DemocracySim

edit_uri: edit/dev/docs/

# Configuration
nav:
    - Home: index.md
    - Teaser: teaser.md
    - Research:
        - Concept: research/research_concept.md
        - Metrics: research/metrics.md
        - Goals: research/goals.md
    - Technical:
        - Overview: technical/technical_overview.md
        - Installation Instructions: technical/installation_instructions.md
        - API Reference:
            - Model (Environment): technical/api/Model.md
            - Area (Territory): technical/api/Area.md
            - Grid Cell: technical/api/ColorCell.md
            - Voting Agent: technical/api/VoteAgent.md
            - Inherited Classes: technical/api/inherited.md
        #- User Guide: technical/user_guide.md #1. Provide step-by-step guides for common project usage.
        #- Examples: technical/examples.md #1. Show key use cases via practical code examples or interactive demos.
        #- Developer Docs: technical/dev_docs.md #Offer guidelines for contributing or extending the project (e.g., folder structure, conventions, CI/CD pipelines).
        - Architecture Overview: technical/architecture_overview.md
    #- Overview: overview.md
    #- Code: the_voting_process_step_by_step.md
    - Mesa: mesa_docs.md

theme:
  name: material
  custom_dir: 'docs/overrides'
  icon:
    repo: octicons/mark-github-16
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to system preference
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - search.share
    - search.highlight
    - search.suggest
    - content.action.edit
# Plugins
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
  - search
  - mkdocstrings:
      default_handler: python

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
