# Project information
site_name: Master thesis "Participation"
site_description: Documentation of the master thesis "Participation"
site_url: https://jurikane.github.io/participation/
site_author: Paul Kühnel

# Repository
repo_url: https://github.com/jurikane/participation

edit_uri: edit/dev/docs/

# Configuration
nav:
    - Home: index.md
    - Teaser: teaser.md
    - Mesa Documentation: mesa_docs.md

theme:
  name: material
  custom_dir: 'docs/overrides'
  icon:
    repo: octicons/mark-github-16
    edit: material/pencil
    view: material/eye
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to system preference
  plugins:
    - git-revision-date-localized:
        enable_creation_date: true
    - search.highlight
    - social
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - search.share
    - content.action.edit
# Plugins
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html